name: 🏆 Generate GitHub Trophies

on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    name: Generate Trophy SVG
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📁 Prepare output directory
        run: mkdir -p profile

      - name: 🏆 Generate trophies
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: print-davidmota
          output_path: profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Commit trophy SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/trophy.svg

          git diff --cached --quiet || git commit -m "Update GitHub trophies"

          git push
